---
title: "Data Translation Assignment"
author: "Lynna Tran"
date: "2/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Load Libraries}
library(tidyverse)
library(jtools)
library(car)
library(readr)
library(purrr)
library(lubridate)
```


```{r Import Data}
Scorecard <- read.csv("Lab3_Rawdata/Most+Recent+Cohorts+(Scorecard+Elements).csv")

name_id <- read_csv("Lab3_Rawdata/id_name_link.csv") %>%
  distinct(schname, .keep_all = TRUE) %>%
  rename(OPEID = opeid) %>%
  rename(UNITID = unitid)

prepend <- function(fname) {
    paste('Lab3_Rawdata/', fname, sep = '')
  }
  
trends <- list.files(path = 'Lab3_Rawdata', pattern = 'trends_up_to_') %>%
  map(prepend) %>%
  map(read_csv) %>%
  reduce(rbind)

```


```{r MERGE DATA}
name_trends_scorecard    <- inner_join(name_id, Scorecard, by = 'OPEID', 'UNITID') %>%
  inner_join(trends, by = 'schname')
```



```{r FILTERING COLLEGES}

#Colleges that predominantly grant bachelors degrees 
bachelors_colleges <- name_trends_scorecard %>%
  filter(PREDDEG == 3) %>%
  select(OPEID, UNITID.x, schname, keyword , keynum, monthorweek , index,  md_earn_wne_p10.REPORTED.EARNINGS)

##Earnings of colleges, adding median earnings columns after filtering 
college_earnings <- bachelors_colleges %>%
  filter(md_earn_wne_p10.REPORTED.EARNINGS != 'NULL') %>%
  filter(md_earn_wne_p10.REPORTED.EARNINGS != 'PrivacySuppressed') %>%
  mutate(median_earnings = as.numeric(md_earn_wne_p10.REPORTED.EARNINGS))

##Checking median earnings values for overall college median earnings 
overall_median_earnings <- median(college_earnings$median_earnings)

##Adding dependent variables to be tested such as High Earning Dummy Variable and SD index based off of schname and index 
##adds t/f for high earning and low earning 
interested_colleges <- college_earnings %>%
  mutate(high_earning = median_earnings > 41800) %>%
  mutate(low_earning  = median_earnings < 41799) %>%
  filter(!is.na(index)) ##filtering out NA indexes because if there's no index value, we can't use it anyways 

##adding sd index
sd_index_colleges <- interested_colleges %>%
  group_by(schname, keynum) %>%
  summarise(sd_index = (index - mean(index)) / sd(index), schname,
            keyword, monthorweek, keynum, median_earnings, sd_index, high_earning, low_earning)
```

```{r GROUP BY DATE}
college_information <- interested_colleges %>% 
  select(schname ,median_earnings, high_earning) %>%
  distinct(schname ,median_earnings, high_earning)

college_sdindex_year2013 <- sd_index_colleges %>% 
  mutate(DATE = substr(monthorweek, 1, 10)) %>%
  mutate(DATE = as.Date(DATE))  %>%
  select(schname, keynum, sd_index, DATE, median_earnings, high_earning) %>%
  filter(between(DATE, as.Date("2013-03-24"), as.Date("2013-12-31"))) %>%
  group_by(schname) %>%
  summarise(sd_index2013 = sum(sd_index))

college_sdindex_year2014 <- sd_index_colleges %>% 
  mutate(DATE = substr(monthorweek, 1, 10)) %>%
  mutate(DATE = as.Date(DATE))  %>%
  select(schname, keynum, sd_index, DATE, median_earnings, high_earning) %>%
  filter(between(DATE, as.Date("2014-01-01"), as.Date("2014-12-31"))) %>%
  group_by(schname) %>%
  summarise(sd_index2014 = sum(sd_index))

college_sdindex_year2015 <- sd_index_colleges %>% 
  mutate(DATE = substr(monthorweek, 1, 10)) %>%
  mutate(DATE = as.Date(DATE))  %>%
  select(schname, keynum, sd_index, DATE, median_earnings, high_earning) %>%
  filter(between(DATE, as.Date("2015-01-01"), as.Date("2015-12-31"))) %>%
  group_by(schname) %>%
  summarise(sd_index2015 = sum(sd_index))

college_sdindex_year2016 <- sd_index_colleges %>% 
  mutate(DATE = substr(monthorweek, 1, 10)) %>%
  mutate(DATE = as.Date(DATE))  %>%
  select(schname, keynum, sd_index, DATE, median_earnings, high_earning) %>%
  filter(between(DATE, as.Date("2016-01-01"), as.Date("2016-12-31"))) %>%
  group_by(schname) %>%
  summarise(sd_index2016 = sum(sd_index))

college_sdindex_year <- left_join(college_sdindex_year2013, college_sdindex_year2014, by = 'schname') %>%
  left_join(college_sdindex_year2015, by = 'schname') %>%
  left_join(college_sdindex_year2016, by = 'schname') %>%
  left_join(college_information, by = 'schname')
```


```{r MODELS}
###2013 MODEL
sd_index_model2013 <- lm(data = college_sdindex_year, median_earnings ~ sd_index2013)

sd_index_model2013HE <- lm(data = college_sdindex_year, median_earnings ~ sd_index2013  + high_earning)


###2014 MODEL
sd_index_model2014 <- lm(data = college_sdindex_year, median_earnings ~ sd_index2014)

sd_index_model2014HE <- lm(data = college_sdindex_year, median_earnings ~ sd_index2014  + high_earning)



###2015 MODEL
sd_index_model2015 <- lm(data = college_sdindex_year, median_earnings ~ sd_index2015)

sd_index_model2015HE <- lm(data = college_sdindex_year, median_earnings ~ sd_index2015  + high_earning)


###2016 MODEL
sd_index_model2016 <- lm(data = college_sdindex_year, median_earnings ~ sd_index2016)

sd_index_model2016HE <- lm(data = college_sdindex_year, median_earnings ~ sd_index2016  + high_earning)


```

```{r COEFFICIENTS TABLES}

export_summs(sd_index_model2013, sd_index_model2014, sd_index_model2015, sd_index_model2016)

export_summs(sd_index_model2013HE, sd_index_model2014HE, sd_index_model2015HE, sd_index_model2016HE)

```


```{r 2013 plots, echo=FALSE}
##2013 model 
ggplot(data = sd_index_model2013, aes(sd_index2013, median_earnings)) +
  geom_point() + ggtitle("All Schools 2013")

hist(rstandard(( sd_index_model2013 )), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of All Schools 2013' )

ggplot(data = sd_index_model2013HE, aes(sd_index2013, median_earnings)) +
  geom_point() + ggtitle("All Schools 2013 with High-Earning Dummy Variable")
```


```{r 2014 plots, echo=FALSE}
ggplot(data = sd_index_model2014, aes(sd_index2014, median_earnings)) +
  geom_point() + ggtitle("All Schools 2014")

hist(rstandard(( sd_index_model2014 )), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of All Schools 2014' )

ggplot(data = sd_index_model2014HE, aes(sd_index2014, median_earnings)) +
  geom_point() + ggtitle("All Schools 2014 with High-Earning Dummy Variable")
```

```{r 2015 plots, echo=FALSE}
ggplot(data = sd_index_model2015, aes(sd_index2015, median_earnings)) +
  geom_point() + ggtitle("All Schools 2015")

hist(rstandard(( sd_index_model2015 )), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of All Schools 2015' )

ggplot(data = sd_index_model2015HE, aes(sd_index2015, median_earnings)) +
  geom_point() + ggtitle("All Schools 2015 with High-Earning Dummy Variable")
```

```{r 2016 plots, echo=FALSE}
ggplot(data = sd_index_model2016, aes(sd_index2016, median_earnings)) +
  geom_point() + ggtitle("All Schools 2016")

hist(rstandard(( sd_index_model2016 )), 
     xlab = "Standardized residuals", main = 'Standardized Residuals of All Schools 2016' )

ggplot(data = sd_index_model2016HE, aes(sd_index2016, median_earnings)) +
  geom_point() + ggtitle("All Schools 2016 with High-Earning Dummy Variable")
```

```{r Plots Comparison, echo=FALSE}

allschoolsyears_plot <- ggplot(data = sd_index_model2013HE, aes(sd_index2013, median_earnings, color = '2013')) +
  geom_point() + 
  geom_point(data = sd_index_model2014HE, aes(sd_index2014, median_earnings, color = "2014")) +
  geom_point(data = sd_index_model2015HE, aes(sd_index2015, median_earnings, color = "2015")) +
  geom_point(data = sd_index_model2016HE, aes(sd_index2016, median_earnings, color = "2016")) +
  ggtitle("All Schools 2013-2016 with High-Earning Dummy Variable") +
  

allschoolsyears_plot + theme(legend.position = 'right')
```

